#配置数据源
spring:
  datasource:    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mysql_2?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations:
    - classpath:/resources/
  #mapper--mapper的路径  
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
   
logging:  level:      com.st.dao: debug

      